config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users, path: '/user', controllers: { registrations: "registrations" }

  root 'pages#index'

  resources :profiles, path: '/user'
  resources :courses

  #Added because of big pictures not loading at the landing page instead.
  get 'pages/index' => 'pages#index'
  get 'profile' => 'profiles#show'
  get 'edit' => 'profiles#edit'
  get 'pages/home' => 'pages#home', as: :home
  post 'learnings/apply' => 'learnings#apply'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id          :integer          not null, primary key
#  title       :text
#  description :text
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Course < ActiveRecord::Base
    belongs_to :mentor, class_name: 'User'
end

app/models/learning.rb
# == Schema Information
#
# Table name: learnings
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  course_id  :integer
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Learning < ActiveRecord::Base
  belongs_to :student, class_name: 'User', foreign_key: "user_id", required: true
  belongs_to :course, required: true

  enum status: [:active, :pending, :progress, :done, :archived]

  validates_uniqueness_of :user_id, scope: :course_id 
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id                  :integer          not null, primary key
#  user_id             :integer
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  birthday            :date
#  personal_info       :text
#  user_email          :string
#  user_phone          :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Profile < ActiveRecord::Base
	belongs_to :user

	validates :personal_info, :birthday, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  role                   :integer
#  first_name             :string
#  last_name              :string
#  banned                 :boolean          default(FALSE), not null
#

class User < ActiveRecord::Base
  
  has_many :courses
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  enum role: { student: 0, mentor: 1, admin: 2 }

  has_one :profile, dependent: :destroy
  after_create :build_profile

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :role, presence: true
  validates_associated :profile

  accepts_nested_attributes_for :profile, allow_destroy: true

  def active_for_authentication?
    super && !self.banned
  end

  def inactive_message
   self.banned ? :banned : super
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def authenticate_admin_user!
     authenticate_user!
     redirect_to root_path unless current_user.admin?
  end

  def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) do |u|
       u.permit([
         :first_name,
         :last_name,
         :email,
         :role,
         :password,
         :password_confirmation,
         profile_attributes: [:user_phone, :user_email, :birthday, :personal_info]
         ])
       end
       devise_parameter_sanitizer.for(:sign_in) do |u|
       u.permit(:first_name, :last_name, :email, :password, :remember_me)
     end
   end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
before_action :authenticate_user!

def index
  @courses = Course.all
end

def create
  @course = Course.new(course_params)
  @course.save
    redirect_to @course
end

def new
  @course = Course.new
    render layout: 'application'
end

def edit
  @course = Course.find(params[:id])
end

def show
  @course = Course.find(params[:id])
end

def update
  @course = Course.find(params[:id])

  if @course.update(course_params)
    redirect_to @course
  else
    render 'edit'
  end
end

def destroy
  @course = Course.find(params[:id])
  @course.destroy
    redirect_to courses_path
end

private
  def course_params
    params.require(:course).permit(:title, :description)
  end

end

app/controllers/learnings_controller.rb
class LearningsController < ActionController::Base

def apply
  @course = Course.find learning_params[:course]		
  user = User.find learning_params[:user_id]

  @learning = Learning.new(course: @course, user_id: user.id, status: :pending)

  @learning.save
  redirect_to @course
end

private
  def learning_params
    params.require(:learning).permit(:course, :user_id, :status)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   layout "dashboard", :only => [:home]

  def index
    redirect_to admin_root_path and return  if user_signed_in?&&current_user.admin?
    redirect_to home_path if user_signed_in?
  end

  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  # def new
  #   @user = current_user
  #   @profile = @user.build_profile
  # end

  def show
    @profile = current_user.profile(params[:id])
    @profile_user = User.find_by(id: current_user.id)
  end

  # def edit
  #   @profile = current_user.profile(params[:id])
  # end
  #
  # def create
  #   @user = current_user
  #   @profile = @user.build_profile(params[:profile])
  #   @profile.user_id = @user.id
  #   @profile.save
  # end
  #
  # def update
  #   @profile = current_user.profile(params[:id])
  #   if @profile.update?
  #     flash[:notices] = ["Your profile was successfully updated"]
  #     redirect_to courses_path
  #   else
  #     render "edit", :alert => "Error occured!"
  #   end
  # end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def after_sign_up_path_for(resource)
    profile_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
	    renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
	    options = {
	        autolink: true,
	        no_intra_emphasis: true,
	        fenced_code_blocks: true,
	        lax_html_blocks: true,
	        strikethrough: true,
	        superscript: true,
	        space_after_headers: true
	    }
	    Redcarpet::Markdown.new(renderer, options).render(text).html_safe
	  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/courses/_form.html.erb
                                    
  <%= form_for @course do |f| %>
<p>                  
  <%= f.label :title %>
  <%= f.text_field :title %>
<p>
<p>
<%= f.label :description %>
<%= f.text_area :description %>
<p>
  <%= f.submit "add course" %>

  <%= link_to 'Back', courses_path %>

  <% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>
 
<%= render 'form' %>

app/views/courses/index.html.erb
<h1>List of Courses</h1>

<% if user_signed_in? %>

  <table class="table">
    <tr>
      <th scope="row"></th>
      <td>Title</th>
      <td>Summary</td>
      <td></td>
    </tr>

    <% @courses.each do |course| %>
      <tr>
        <th scope="row"></th>
        <td><%= course.title %></td>
        <td><%= course.description %></td>
        <td><%= link_to "Show", course %></td>
        <td><%= link_to "Subscribe", learnings_apply_path(learning: {user_id: current_user.id, course: course.id, status: :pending }), method: :post %></td>
        <% if current_user.mentor? %>
        <td><%= link_to 'Edit', edit_course_path(course)%></td>
        <td><%= link_to 'Destroy', course , method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </td>
      </tr>
<% end %>


  </table>

<% if current_user.mentor? %>  
  <%= link_to "New course", new_course_path %>
<% end %>

<% else %>
  <%= link_to "Sing in", new_user_session_path %>

<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>
 
<%= render 'form' %>

app/views/courses/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>
<p>
  <strong>Description:</strong>
  <%= markdown(@course.description) %>
</p>

  <%= link_to 'Back', courses_path %>

app/views/layouts/_navigation.html.erb
<!-- NAVIGATION -->
<div id="menu">
	<nav class="navbar-wrapper navbar-default">
		<div class="container">
			  <div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-backyard">
				  <span class="sr-only">Toggle navigation</span>
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
				  <span class="icon-bar"></span>
				</button>
				<%= link_to image_tag("landing_page/mentority.png"), root_path, :class => "navbar-brand site-name" %>
			  </div>

			  <div id="navbar-scroll" class="collapse navbar-collapse navbar-backyard navbar-right">
				<ul class="nav navbar-nav">
					<% if current_user %>
						<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %> </li>
					<% end %>
				</ul>
			  </div>
		</div>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mentority</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic" />
</head>
<body>
	<% unless current_page?(root_path) %>
		<%= render 'layouts/navigation' %>
	<% end %>
<%= yield %>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mentority</title>
  <%= stylesheet_link_tag    'dashboard', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'dashboard', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!--  wrapper -->
  <div id="wrapper">
      <!-- navbar top -->
      <nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="navbar">
          <!-- navbar-header -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.html">
                  <%= link_to image_tag("landing_page/mentority.png"), root_path, :class => "navbar-brand site-name" %>
              </a>
          </div>
          <!-- end navbar-header -->
          <!-- navbar-top-links -->
          <ul class="nav navbar-top-links navbar-right">
              <!-- main dropdown -->
              <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      <span class="top-label label label-danger">3</span><i class="fa fa-envelope fa-3x"></i>
                  </a>
                  <!-- dropdown-messages -->
                  <ul class="dropdown-menu dropdown-messages">
                      <li>
                          <a href="#">
                              <div>
                                  <strong><span class=" label label-danger">Andrew Smith</span></strong>
                                  <span class="pull-right text-muted">
                                      <em>Yesterday</em>
                                  </span>
                              </div>
                              <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                          </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a href="#">
                              <div>
                                  <strong><span class=" label label-info">Jonney Depp</span></strong>
                                  <span class="pull-right text-muted">
                                      <em>Yesterday</em>
                                  </span>
                              </div>
                              <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                          </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a href="#">
                              <div>
                                  <strong><span class=" label label-success">Jonney Depp</span></strong>
                                  <span class="pull-right text-muted">
                                      <em>Yesterday</em>
                                  </span>
                              </div>
                              <div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
                          </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a class="text-center" href="#">
                              <strong>Read All Messages</strong>
                              <i class="fa fa-angle-right"></i>
                          </a>
                      </li>
                  </ul>
                  <!-- end dropdown-messages -->
              </li>

              <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      <span class="top-label label label-success">4</span>  <i class="fa fa-tasks fa-3x"></i>
                  </a>
                  <!-- dropdown tasks -->
                  <ul class="dropdown-menu dropdown-tasks">
                      <li>
                          <a href="#">
                              <div>
                                  <p>
                                      <strong>Task 1</strong>
                                      <span class="pull-right text-muted">40% Complete</span>
                                  </p>
                                  <div class="progress progress-striped active">
                                      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                          <span class="sr-only">40% Complete (success)</span>
                                      </div>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a href="#">
                              <div>
                                  <p>
                                      <strong>Task 2</strong>
                                      <span class="pull-right text-muted">20% Complete</span>
                                  </p>
                                  <div class="progress progress-striped active">
                                      <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
                                          <span class="sr-only">20% Complete</span>
                                      </div>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a href="#">
                              <div>
                                  <p>
                                      <strong>Task 3</strong>
                                      <span class="pull-right text-muted">60% Complete</span>
                                  </p>
                                  <div class="progress progress-striped active">
                                      <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                                          <span class="sr-only">60% Complete (warning)</span>
                                      </div>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a href="#">
                              <div>
                                  <p>
                                      <strong>Task 4</strong>
                                      <span class="pull-right text-muted">80% Complete</span>
                                  </p>
                                  <div class="progress progress-striped active">
                                      <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                                          <span class="sr-only">80% Complete (danger)</span>
                                      </div>
                                  </div>
                              </div>
                          </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a class="text-center" href="#">
                              <strong>See All Tasks</strong>
                              <i class="fa fa-angle-right"></i>
                          </a>
                      </li>
                  </ul>
                  <!-- end dropdown-tasks -->
              </li>

              <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      <span class="top-label label label-warning">5</span>  <i class="fa fa-bell fa-3x"></i>
                  </a>
                  <!-- dropdown alerts-->
                  <ul class="dropdown-menu dropdown-alerts">
                      <li>
                          <a href="#">
                              <div>
                                  <i class="fa fa-comment fa-fw"></i>New Comment
                                  <span class="pull-right text-muted small">4 minutes ago</span>
                              </div>
                          </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a href="#">
                              <div>
                                  <i class="fa fa-twitter fa-fw"></i>3 New Followers
                                  <span class="pull-right text-muted small">12 minutes ago</span>
                              </div>
                          </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a href="#">
                              <div>
                                  <i class="fa fa-envelope fa-fw"></i>Message Sent
                                  <span class="pull-right text-muted small">4 minutes ago</span>
                              </div>
                          </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a href="#">
                              <div>
                                  <i class="fa fa-tasks fa-fw"></i>New Task
                                  <span class="pull-right text-muted small">4 minutes ago</span>
                              </div>
                          </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a href="#">
                              <div>
                                  <i class="fa fa-upload fa-fw"></i>Server Rebooted
                                  <span class="pull-right text-muted small">4 minutes ago</span>
                              </div>
                          </a>
                      </li>
                      <li class="divider"></li>
                      <li>
                          <a class="text-center" href="#">
                              <strong>See All Alerts</strong>
                              <i class="fa fa-angle-right"></i>
                          </a>
                      </li>
                  </ul>
                  <!-- end dropdown-alerts -->
              </li>

              <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      <i class="fa fa-user fa-3x"></i>
                  </a>
                  <!-- dropdown user-->
                  <ul class="dropdown-menu dropdown-user">
                     <li><a rel="nofollow" href="/edit"><i class="fa fa-user fa-fw"></i>User Profile</a>
                     </li>
                      <li><a href="#"><i class="fa fa-gear fa-fw"></i>Settings</a>
                      </li>
                      <li class="divider"></li>
                      <li><a rel="nofollow" data-method="delete" href="/user/sign_out"><i class="fa fa-sign-out fa-fw"></i>Logout</a>
                      </li>
                  </ul>
                  <!-- end dropdown-user -->
              </li>
              <!-- end main dropdown -->
          </ul>
          <!-- end navbar-top-links -->

      </nav>
      <!-- end navbar top -->
      <%= yield %>
</body>
</html>

app/views/layouts/dashboard/_mentor_navbar_side.html.erb
<!-- navbar side -->
<nav class="navbar-default navbar-static-side" role="navigation">
    <!-- sidebar-collapse -->
    <div class="sidebar-collapse">
        <!-- side-menu -->
        <ul class="nav" id="side-menu">
            <li>
                <!-- user image section-->
                <div class="user-section">
                    <div class="user-section-inner">
                      <%=image_tag("dashboard/user.jpg", alt:"") %>
                    </div>
                    <div class="user-info">
                        <div><%=(current_user.first_name)%> <strong><%=(current_user.last_name)%></strong></div>
                        <div class="user-text-online">
                            <span class="user-circle-online btn btn-success btn-circle "></span>&nbsp;Online
                        </div>
                    </div>
                </div>
                <!--end user image section-->
            </li>
            <li class="sidebar-search">
                <!-- search section-->
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!--end search section-->
            </li>
            <li class="selected">
                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i>Dashboard</a>
            </li>
             <li>
                <a href="#"><i class="fa fa-user fa-fw"></i>Mentors</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-user fa-fw"></i>Students</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-edit fa-fw"></i>Messages</a>
            </li>
        </ul>
        <!-- end side-menu -->
    </div>
    <!-- end sidebar-collapse -->
</nav>
<!-- end navbar side -->

app/views/layouts/dashboard/_student_navbar_side.html.erb
<!-- navbar side -->
<nav class="navbar-default navbar-static-side" role="navigation">
    <!-- sidebar-collapse -->
    <div class="sidebar-collapse">
        <!-- side-menu -->
        <ul class="nav" id="side-menu">
            <li>
                <!-- user image section-->
                <div class="user-section">
                    <div class="user-section-inner">
                      <%=image_tag("dashboard/user.jpg", alt:"") %>
                    </div>
                    <div class="user-info">
                        <div><%=(current_user.first_name)%> <strong><%=(current_user.last_name)%></strong></div>
                        <div class="user-text-online">
                            <span class="user-circle-online btn btn-success btn-circle "></span>&nbsp;Online
                        </div>
                    </div>
                </div>
                <!--end user image section-->
            </li>
            <li class="sidebar-search">
                <!-- search section-->
                <div class="input-group custom-search-form">
                    <input type="text" class="form-control" placeholder="Search...">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
                <!--end search section-->
            </li>
            <li class="selected">
                <a href="index.html"><i class="fa fa-dashboard fa-fw"></i>Dashboard</a>
            </li>
             <li>
                <a href="#"><i class="fa fa-user fa-fw"></i>Mentors</a>
            </li>
            <li>
                <a href="#"><i class="fa fa-edit fa-fw"></i>Messages</a>
            </li>
        </ul>
        <!-- end side-menu -->
    </div>
    <!-- end sidebar-collapse -->
</nav>
<!-- end navbar side -->

app/views/pages/home.html.erb
 <%if current_user.student?%>
 <%= render partial: "layouts/dashboard/student"%>
 <%end%>
 <%if current_user.mentor?%>
 <%= render partial: "layouts/dashboard/mentor"%>
 <%end%>>

app/views/profiles/show.html.erb
<br/>
<div class="container">
  <div class="row">
  	<div class="col-md-6">

      <div class="panel panel-default">
			<div class="panel-body">
              		<div class="row">
                        <div class="col-xs-12 col-sm-8">
                            <h2><%= @profile_user.first_name %> <%= @profile_user.last_name %></h2>
                            <p><strong>Role: </strong> <%= @profile_user.role %> </p>
                            <p><strong>Hobbies: </strong> Read, out with friends, listen to music, draw and learn new things. </p>
                            <p><strong>Skills: </strong>
                                <span class="label label-info tags">html5</span>
                                <span class="label label-info tags">css3</span>
                                <span class="label label-info tags">jquery</span>
                                <span class="label label-info tags">bootstrap3</span>
                            </p>
                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4 text-center">
                                <img src="http://api.randomuser.me/portraits/men/49.jpg" alt="" class="center-block img-circle img-responsive">
                                <ul class="list-inline ratings text-center" title="Ratings">
                                  <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
                                  <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
                                  <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
                                  <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
                                  <li><a href="#"><span class="fa fa-star fa-lg"></span></a></li>
                                </ul>
                        </div><!--/col-->

                        <div class="col-xs-12 col-sm-4">
                            <h2><strong> 20,7K </strong></h2>
                            <p><small>Followers</small></p>
                            <button class="btn btn-success btn-block"><span class="fa fa-plus-circle"></span> Follow </button>
                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4">
                            <h2><strong>245</strong></h2>
                            <p><small>Following</small></p>
                            <button class="btn btn-info btn-block"><span class="fa fa-user"></span> View Profile </button>
                        </div><!--/col-->
                        <div class="col-xs-12 col-sm-4">
                            <h2><strong>43</strong></h2>
                            <p><small>Snippets</small></p>
														<%= link_to "Edit profile", edit_user_registration_path, class: "btn btn-warning btn-block" %>
                        </div><!--/col-->
              		</div><!--/row-->
              </div><!--/panel-body-->
          </div><!--/panel-->
    </div>
  </div>
</div>